APP_ENV=local
APP_DEBUG=true
APP_KEY=iXDJ5rz7QHkzPNv0CcISOBCaLccCHenp

DB_HOST=localhost
DB_DATABASE=pollflare
DB_USERNAME=root
DB_PASSWORD=null
DB_LOG=true

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=localhost
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=mandrill
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

SITE_HOST=local.pollflare.com
ADMIN_HOST=admin.local.pollflare.com
API_HOST=api.local.pollflare.com

MANDRILL_SECRET=LJCBoJpHFF7ZRrFqgu9Q2g

FB_APP_ID=1925759900981781
FB_APP_SECRET=13cd51694b7f1d24536f312fbd7bf38e
